/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import classes.ExcelExport;
import classes.Stock;
import static gui.login.txtUserName;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author BhavyaShah
 */
public class searchDatabase extends javax.swing.JFrame {
JFileChooser fc;
    File f;
    static String path,user;
    /**
     * Creates new form search
     */
    public searchDatabase() {
        initComponents();
        Show_Stock_In_JTable();
    }
    
    public Connection getConnection()
    {
        Connection con;
        try
        {
            con =  DriverManager.getConnection("jdbc:postgresql://localhost:5432/StylingHouse","postgres","1234");
            return con;
        }
        catch(Exception e)
                {
                    e.printStackTrace();
                    return null;
                }
    }
    
    public ArrayList<Stock> getStockList()
    {
        ArrayList<Stock> stockList =  new ArrayList<Stock>();
        Connection  connection =  getConnection();
        String query = "SELECT * FROM search";
        Statement st;
        ResultSet rs;
        try
        {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Stock customer;
            while(rs.next())
            {
                customer = new Stock(rs.getInt("id"),rs.getString("ProductName"),
                        rs.getString("DateOfAdditionToStock"));
                stockList.add(customer);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return stockList;
    }
   
    public void Show_Stock_In_JTable()
    {
        ArrayList<Stock> list = getStockList();
        DefaultTableModel model = (DefaultTableModel)jTable_Show_Stock.getModel();
        Object[] row = new Object[3];
        for(int i=0; i<list.size();i++)
        {
            row[0] = list.get(i).getID();
            row[1] = list.get(i).getNameOfProduct();
            row[2] = list.get(i).getDateAddedToStock();
            
            model.addRow(row);
        }
    }
    
    public void executeSQLQuery(String query, String message)
    {
        Connection con = getConnection();
        Statement st;
        try
        {
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
                JOptionPane.showMessageDialog(null,"Data "+message+"Succefully");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Data Not "+message);
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Show_Stock = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNameOfProduct = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDateAddedToStock = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        btnAddToStock = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDeleteCustomerFromDatabase = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Product"));

        jLabel7.setFont(new java.awt.Font("Harrington", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("The Image And Styling House");

        jTable_Show_Stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#ID", "Name Of Product", "Date Of Addition To Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Show_Stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Show_StockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Show_Stock);

        jLabel2.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        jLabel2.setText("#ID");

        txtID.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        jLabel3.setText("Name Of Product");

        txtNameOfProduct.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        jLabel4.setText("Date Added To Stock");

        txtDateAddedToStock.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        txtDateAddedToStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateAddedToStockActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon("/Users/bhavyashah/Desktop/IBDP/SUBJECTS/COMPUTERSCIENCEIA20162017/images/Reset_button-1 copy.png")); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAddToStock.setBackground(new java.awt.Color(255, 255, 255));
        btnAddToStock.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        btnAddToStock.setIcon(new javax.swing.ImageIcon("/Users/bhavyashah/Desktop/IBDP/SUBJECTS/COMPUTERSCIENCEIA20162017/images/storage copy.png")); // NOI18N
        btnAddToStock.setText("Add To Stock");
        btnAddToStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToStockActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon("/Users/bhavyashah/Desktop/IBDP/SUBJECTS/COMPUTERSCIENCEIA20162017/images/file_edit copy.png")); // NOI18N
        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDeleteCustomerFromDatabase.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteCustomerFromDatabase.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        btnDeleteCustomerFromDatabase.setIcon(new javax.swing.ImageIcon("/Users/bhavyashah/Desktop/IBDP/SUBJECTS/COMPUTERSCIENCEIA20162017/images/Delete_Icon copy.png")); // NOI18N
        btnDeleteCustomerFromDatabase.setText("Delete");
        btnDeleteCustomerFromDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerFromDatabaseActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon("/Users/bhavyashah/Desktop/IBDP/SUBJECTS/COMPUTERSCIENCEIA20162017/images/13165939071654987882logout-md copy.png")); // NOI18N
        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnExportExcel.setBackground(new java.awt.Color(255, 255, 255));
        btnExportExcel.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        btnExportExcel.setText("Export to Excel");
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon("/Users/bhavyashah/Desktop/IBDP/SUBJECTS/COMPUTERSCIENCEIA20162017/images/back-return-button-png-18 copy.png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDateAddedToStock, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNameOfProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(txtID)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDeleteCustomerFromDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAddToStock, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(btnExportExcel, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                        .addContainerGap())))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNameOfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDateAddedToStock, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh)
                            .addComponent(btnAddToStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteCustomerFromDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateAddedToStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateAddedToStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateAddedToStockActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String name = txtNameOfProduct.getText();
        String dateadded = txtDateAddedToStock.getText();
        String query = "UPDATE public.search SET id=\'"+id+"\', ProductName=\'"+name+"\', DateOfAdditionToStock=\'"+dateadded+"\' WHERE id="+id;
        executeSQLQuery(query,"Updated");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteCustomerFromDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerFromDatabaseActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String query = "DELETE FROM public.search WHERE id="+id;
       executeSQLQuery(query,"Deleted");
    }//GEN-LAST:event_btnDeleteCustomerFromDatabaseActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddToStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToStockActionPerformed
        // TODO add your handling code here:
        if(txtID.getText().trim().equals("") && txtNameOfProduct.getText().trim().equals("") && txtDateAddedToStock.getText().trim().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Cannot leave fields Empty" , "Error" , JOptionPane.WARNING_MESSAGE);
        
            if(!(Pattern.matches("^[a-zA-z]+$", txtNameOfProduct.getText())))
            {
                JOptionPane.showMessageDialog(null, "The name is invalid", "Error",JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
        String ID = txtID.getText();
        String NameOfProduct = txtNameOfProduct.getText();
        String DateAddedToStock = txtDateAddedToStock.getText();
        
        Connection con = null;
        Statement stmt = null;
        
        try
        {
        String url = "jdbc:postgresql://localhost:5432/StylingHouse";
        String username = "postgres";
        String password = "1234";
        con = DriverManager.getConnection(url, username, password);
        PreparedStatement ps = con.prepareStatement("insert into search values(\'"+ID+"\',\'"+NameOfProduct+
            "\', \'"+DateAddedToStock+"\')");
        int status = ps.executeUpdate();
        if (status > 0) 
        {
            JOptionPane.showMessageDialog(null, "Inserted into Database", "Success", JOptionPane.INFORMATION_MESSAGE);
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Not able Insert into Database", "Error", JOptionPane.WARNING_MESSAGE);
        }
        con.close();
        ps.close();
        } 
        catch (Exception e) 
        {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
    }//GEN-LAST:event_btnAddToStockActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new searchDatabase().setVisible(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        // TODO add your handling code here:
       try
       {
           ExcelExport exp = new ExcelExport();
           exp.exportTable(jTable_Show_Stock, new File ("stock.xls"));
       }catch(IOException e)
       {
           e.getMessage();
       }
    }//GEN-LAST:event_btnExportExcelActionPerformed

    private void jTable_Show_StockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Show_StockMouseClicked
        // TODO add your handling code here:
        int i = jTable_Show_Stock.getSelectedRow();
        TableModel model = jTable_Show_Stock.getModel();
        txtID.setText(model.getValueAt(i,0).toString());
        txtNameOfProduct.setText(model.getValueAt(i,1).toString());
        txtDateAddedToStock.setText(model.getValueAt(i,2).toString());
    }//GEN-LAST:event_jTable_Show_StockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToStock;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteCustomerFromDatabase;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Show_Stock;
    private javax.swing.JTextField txtDateAddedToStock;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNameOfProduct;
    // End of variables declaration//GEN-END:variables
}
